article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='articles_list'),
    path('cat/<str:category>', views.ArticlesListView.as_view(), name='articles_by_category_list'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
]

eshop_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

urlpatterns = [
    # debug = false
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^STATIC/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    path('', include('home_module.urls'), name='homemodule'),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('robot-training/', include('robot_training.urls')),
    path('software_training/', include('software_training.urls')),
    path('automation-training/', include('industrial_automation.urls')),
    path('products/', include('product_module.urls')),
    path('projects/', include('ariana_projects.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('m-driver', views.MDRIVER.as_view(), name='about_page'),
]

article_module/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from jalali_date import date2jalali
from django.utils.text import slugify
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def get_absolute_url(self):
        return reverse('articles_list', args=[self.id,])

article_module/views.py
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from article_module.models import Article, ArticleCategory
from django.template.loader import render_to_string


class ArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'article_module/articles_page.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        query = super(ArticlesListView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.filter(is_active=True, parent_id=None)

    context = {
        'main_categories': article_main_categories
    }
    return render(request, 'article_module/components/article_categories_component.html', context)

article_module/templates/article_module/components/article_categories_component.html
<h2>دسته بندی مقالات</h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->


    {% for main_category in main_categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {% if main_category.articlecategory_set.all %}
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{ main_category.url_title }}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {{ main_category.title }}
                        </a>

                    {% else %}
                        <a href="{% url 'articles_by_category_list' category=main_category.url_title %}">
                            {{ main_category.title }}
                        </a>
                    {% endif %}
                </h4>
            </div>
            {% if main_category.articlecategory_set.all %}
                <div id="{{ main_category.url_title }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for sub_category in main_category.articlecategory_set.all %}
                                <li><a href="{% url 'articles_by_category_list' category=sub_category.url_title %}"> {{ sub_category.title }} </a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}


</div>